In [ ]:
# introduction to pandas--->
# pandas is an open-source llibray of python which usused for handle data manipulations.

In [ ]:
# !pip install pandas

In [ ]:
import pandas as pd

In [ ]:
# data structure of pands:
# (1) Series
# (2) Dataframe

In [ ]:

# (1). series---> it is one dimenstional array and it returns only values not column name.

In [ ]:
a=pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
type(a)

pandas.core.series.Series

In [ ]:
# (2). Dataframe :: -> it is multi -dimensional array and it return values with column name.

In [ ]:

# Task ::: we have to crete a datafrane of employees in which column are
# emp_id,emp_name,department,salary,working_hours

In [ ]:
a = {
    "Emp_id": ['A101','A102','A103','A104','A105','A106'],
    "Emp_name": ['Sam', 'Rahul', 'Ankit', 'Alice', 'Saurav', 'Mohit'],
    "Department": ['IT', 'Operations', 'IT', 'IT', 'Operations', 'IT'],
    "Salary": [20000, 25000, 30000, 40000, 45000, 35000],
    "Working_hours": [8,9,8,9,8,9]
}

In [ ]:
df=pd.DataFrame(a)
df

  Emp_id Emp_name  Department  Salary  Working_hours
0   A101      Sam          IT   20000              8
1   A102    Rahul  Operations   25000              9
2   A103    Ankit          IT   30000              8
3   A104    Alice          IT   40000              9
4   A105   Saurav  Operations   45000              8
5   A106    Mohit          IT   35000              9

In [ ]:
# How can we export the dataframe into CSV data?

In [ ]:
df.to_csv("emp_info.csv")  # to_csv mean export your data into csv file

In [ ]:
df.to_csv("new_emp_info.csv",index=False) #indec=false means it will remove unname column.

In [ ]:
# How to using csv data using pandas

In [ ]:
df=pd.read_csv("/content/new_emp_info.csv")
df

  Emp_id Emp_name  Department  Salary  Working_hours
0   A101      Sam          IT   20000              8
1   A102    Rahul  Operations   25000              9
2   A103    Ankit          IT   30000              8
3   A104    Alice          IT   40000              9
4   A105   Saurav  Operations   45000              8
5   A106    Mohit          IT   35000              9

In [ ]:
df =pd.read_csv("/content/new_emp_info.csv",encoding=1)
df

TypeError: lookup() argument must be str, not int

In [ ]:
# shoees range 2000 to 5000
# massuri best palce to vist

In [ ]:
df =pd.read_csv("/flipkart.himanshu.csv" )

FileNotFoundError: [Errno 2] No such file or directory: '/flipkart.himanshu.csv'

In [ ]:
df

  Emp_id Emp_name  Department  Salary  Working_hours
0   A101      Sam          IT   20000              8
1   A102    Rahul  Operations   25000              9
2   A103    Ankit          IT   30000              8
3   A104    Alice          IT   40000              9
4   A105   Saurav  Operations   45000              8
5   A106    Mohit          IT   35000              9

In [ ]:
df['Company'].value_counts()

KeyError: 'Company'

In [ ]:
df.describe()

In [ ]:
df.head()
df.tail()
df[1:5]

In [ ]:
df.loc[1:2,['Company','Type',"Discount",'price','off']]
df.iloc[1:2,[1,2,3,4]]

In [ ]:
df['off'].value_counts()
df.isnull().sum()
df.dtypes
df['Company'].value_counts()

In [ ]:
df['Company']=df['Company'].map({'Duke':'1','PUMA':'2','Cult':'3','ADIDAS':'4','New Balance':'5'})
df

In [ ]:
df =pd.read_csv("/massuriii.csv" )

In [ ]:
df

In [ ]:
df=pd.read_csv("/covid_toy.csv")
df

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

In [ ]:
df['fever'] = df['fever'].fillna(df['fever']).mean()

In [ ]:
df.isnull().sum()

In [ ]:
# loc() and iloc()
# df.loc[row_range,column_name]----> start value include and last value include.
# df.iloc[row_range,column_range]---> start value include but last value exclude

In [ ]:
df.loc[5:10,['age','fever','cough']]

In [ ]:
df.head(11)

In [ ]:
df['gender'].value_count()

In [ ]:
df.head(2)

In [ ]:
df['gender'].value_counts()

In [ ]:
df.head(2)

In [ ]:
df['gender'] = df['gender'].map({'Male':1,'Female':0})
df['cough'] = df['cough'].map({"mild":0,"strong":1})

In [ ]:
df['has_covid'] =df["has_covide"].map

In [ ]:
df.drop(columns = ['city'])

In [ ]:
df=df.drop(column =['city']) # how to drop or delet one or more columns

In [ ]:
# df.head

In [ ]:
df.sort_index() #sort the data

In [ ]:
df=df.rename(columns = {'cough':"updated_cough"})

In [ ]:
df['Age']=df[age].add(10)

In [ ]:
# df.head(5)

In [ ]:
df=df.drop(columns = ['Age'])

In [ ]:
df.head(2)

In [ ]:
df[["age","fever"]]  # using this method,we can filter the data

In [ ]:
df=pd.read_csv("/content/flipkart.himanshu.csv")
df