In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/placement - placement.csv')
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [ ]:
df.head() #top 5 data

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [ ]:
df.tail() #bottom  5 data

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [ ]:
df.describe () # staties view

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [ ]:
top_left_corner_df =df.iloc[:4,:3] #iloc[row_range,column_range]
top_left_corner_df

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [ ]:
df.loc[1:3,['cgpa','placed']]

   cgpa  placed
1  6.17       0
2  8.27       1
3  6.88       1

In [ ]:
s=df.axes
s

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='object')]

In [ ]:
p=df.dtypes
p

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [ ]:
b=df.empty    # it returns true if there any missing data in dataframe otherwise false
b

False

In [ ]:
df.isnull().sum # for check missing values.

<bound method DataFrame.sum of      cgpa  resume_score  placed
0   False         False   False
1   False         False   False
2   False         False   False
3   False         False   False
4   False         False   False
..    ...           ...     ...
95  False         False   False
96  False         False   False
97  False         False   False
98  False         False   False
99  False         False   False

[100 rows x 3 columns]>

In [ ]:
df.dropna() # for remove missing row

In [ ]:
i=df.ndim # number of axes(it is 2)
i

2

In [ ]:
t=df.shape #shape =n(rows),n(columns)
t
df.shape[0] #total rows in data
df.shape[1] #total columns in data

3

In [ ]:
d= df.size    #row count * column count
d

300

In [ ]:
a=df.values   # get a numpy array for df
a

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
       [9.05, 8.21, 1.  ],
       [6.  , 8.72, 0.  ],
       [7.5 , 6.19, 1.  ],
       [8.25, 5.32, 1.  ],
       [8.68, 5.15, 1.  ],
       [6.9 , 6.91, 1.  ],
       [8.21, 7.95, 1.  ],
       [5.47, 5.92, 0.  ],
       [8.1 , 5.44, 1.  ],
       [5.83, 5.21, 0.  ],
       [7.05, 8.14, 1.  ],
       [5.54, 6.57, 0.  ],
       [5.46, 6.73, 0.  ],
       [8.22, 6.74, 1.  ],
       [6.54, 7.39, 0.  ],
       [5.9 , 7.5 , 0.  ],
       [6.  , 7.16, 0.  ],
       [5.92, 7.18, 0.  ],
       [6.94, 6.87, 1.  ],
       [6.13, 6.43, 0.  ],
       [6.34, 7.21, 0.  ],
       [6.47, 7.37, 0.  ],
       [5.95, 7.57, 0.  ],
       [5.87, 6.64, 0.  ],
       [6.89, 7.96, 1.  ],
       [5.75, 8.43, 0.  ],
       [8.65, 7.58, 1.  ],
       [7.93, 8.09, 1.  ],
       [6.04, 8.75, 0.  ],
       [8.35, 8.02, 1.  ],
       [6.59, 6.81, 1.  ],
       [6.01, 7.49, 0.  ],
       [8.06, 9.06, 1.  ],
       [7.12, 7.41, 1.  ],
       [7.34, 8.22, 1.  ],
       [7.63, 7.98, 1.  ],
       [5.76, 6.48, 0.  ],
       [5.54, 7.36, 0.  ],
       [6.34, 7.94, 1.  ],
       [9.4 , 5.5 , 1.  ],
       [5.88, 6.92, 0.  ],
       [5.79, 5.66, 0.  ],
       [5.27, 7.28, 0.  ],
       [7.83, 7.7 , 1.  ],
       [6.12, 6.72, 0.  ],
       [7.92, 6.06, 1.  ],
       [7.6 , 8.08, 1.  ],
       [5.76, 6.49, 0.  ],
       [6.72, 5.46, 0.  ],
       [6.18, 5.76, 0.  ],
       [5.62, 5.05, 0.  ],
       [8.07, 6.07, 1.  ],
       [5.99, 7.49, 0.  ],
       [5.85, 5.56, 0.  ],
       [8.28, 6.3 , 1.  ],
       [5.43, 6.18, 0.  ],
       [9.31, 7.39, 1.  ],
       [8.01, 4.95, 1.  ],
       [6.33, 6.38, 0.  ],
       [8.23, 7.76, 1.  ],
       [6.65, 7.78, 0.  ],
       [8.14, 5.63, 1.  ],
       [6.09, 6.61, 0.  ]])

In [ ]:
df=df.copy()

In [ ]:
p=df.sort_values(by='resume_score')  #it short the value from spacif datafrsme
p

    cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

In [ ]:
r=df.sort_index()
r

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [ ]:
df['cgpa']=df['cgpa'].astype(int)

In [ ]:
df.dtypes

cgpa              int64
resume_score    float64
placed            int64
dtype: object

In [ ]:
df['cgpa'] =df['cgpa'].astype(str)

In [ ]:
df.dtypes

cgpa             object
resume_score    float64
placed            int64
dtype: object

In [ ]:
df['resume_score'] =df['cgpa'].astype(int)

In [ ]:
df.dtypes

cgpa            int64
resume_score    int64
placed          int64
dtype: object

In [ ]:
t =df.add(4)
t

    cgpa  resume_score  placed
0     20            12       5
1     18            10       4
2     20            12       5
3     18            10       5
4     19            11       5
..   ...           ...     ...
95    18            10       4
96    20            12       5
97    18            10       4
98    20            12       5
99    18            10       4

[100 rows x 3 columns]

In [ ]:
s=df.count()
s

cgpa            100
resume_score    100
placed          100
dtype: int64

In [ ]:
p=df.max()
p

cgpa            17
resume_score     9
placed           1
dtype: int64

In [ ]:
q=df.min()
q

cgpa            13
resume_score     5
placed           0
dtype: int64

In [ ]:
g=df.filter( items = ['cgpa','placed'])
g
df[['cgpa','placed']] # secound option of filtering

    cgpa  placed
0     16       1
1     14       0
2     16       1
3     14       1
4     15       1
..   ...     ...
95    14       0
96    16       1
97    14       0
98    16       1
99    14       0

[100 rows x 2 columns]

In [ ]:
s=df.filter(items =[5,6],axis =0) ## axis = 0 means row wise operation
s

   cgpa  resume_score  placed
5    16             8       1
6    13             5       0

In [ ]:
t= df.filter(like='5',axis=0)
t

    cgpa  resume_score  placed
5     16             8       1
15    16             8       1
25    15             7       1
35    16             8       1
45    16             8       1
50    16             8       1
51    14             6       0
52    13             5       0
53    14             6       0
54    13             5       0
55    14             6       1
56    14             6       0
57    14             6       0
58    14             6       0
59    13             5       0
65    14             6       0
75    14             6       1
85    14             6       0
95    14             6       0

In [ ]:
p=df.rename(columns={'cgpa':'updated_cgpa','resume_score' : 'semester_marks'}) # how to rename a column
p

    updated_cgpa  semester_marks  placed
0             16               8       1
1             14               6       0
2             16               8       1
3             14               6       1
4             15               7       1
..           ...             ...     ...
95            14               6       0
96            16               8       1
97            14               6       0
98            16               8       1
99            14               6       0

[100 rows x 3 columns]

In [ ]:
df['half']=df['cgpa'].where(df['cgpa']>7,other =0)
df.head(10)

   cgpa  resume_score  placed  half
0    16             8       1    16
1    14             6       0    14
2    16             8       1    16
3    14             6       1    14
4    15             7       1    15
5    16             8       1    16
6    13             5       0    13
7    14             6       0    14
8    14             6       0    14
9    15             7       1    15

In [ ]:
df=pd.read.csv('')

In [ ]:
df.groupby('has_covid').size()